@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 6f3e8cd858ca9cc57428ceebc06042936b17588c1efe8d7079ebc5de40b7c9906bc314ac2ceb9b0b2ef96dbf81a6807ef9d4c11db7a9f0ccda2edef338ced9a2

{
    "name": "John Doe",
    "password": "password",
    "email": "test@gmail.com"
}