@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 699d3034938972c22b0ee4070d1a7a76497bce0d657e83ebd42e859a7c73090ada74ac4ec04a7df16e75f8a4ac890a75e364449ffeacdc38590a70d9497fd2ba

{
    "name": "John Doe",
    "password": "password",
    "email": "test@gmail.com"
}