@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: c47450f111a2722fef4076e6e3addb42cef7cae133fa6be22a73e3baa1066287c60e3ddea9de9ca00a4422b49b87243e777d4e48e07e2c8eab2c44d82455218b

{
    "name": "John Doe",
    "password": "password",
    "email": "test@gmail.com"
}